FROM python:3.12

RUN apt-get update

WORKDIR /opt/app

COPY pyproject.toml ./
COPY poetry.lock ./

RUN apt-get update \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev

COPY tests tests
COPY lib lib

CMD ["pytest"]
